version: '3.4'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Photo_album/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: photo_album
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata
volumes:
  postgres:
    driver: local