# Generated by Django 4.1.5 on 2023-01-06 09:30

import Photo_Album.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Photo_Album.core.validators.validate_letters])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Photo_Album.core.validators.validate_letters])),
                ('subject', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), Photo_Album.core.validators.validate_letters])),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(10)])),
                ('massage_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
