# Generated by Django 4.1.5 on 2023-01-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
