# Generated by Django 4.1.5 on 2023-01-13 19:17

import Photo_Album.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[Photo_Album.core.validators.validate_letters]),
        ),
    ]
