# Generated by Django 4.1.5 on 2023-01-14 07:59

import Photo_Album.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[Photo_Album.core.validators.validate_letters]),
        ),
    ]
